version: '3.8'

services:
  mysql:
    container_name: mysql_db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: javaweb
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf  # Montar tu archivo de configuración
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Montar tu script de inicialización
    ports:
      - "3307:3306"
  webapp:
    container_name: webapp
    image: tomcat:10.1.24-jdk21-temurin-jammy
    restart: always
    volumes:
      - ./target/PaginaWebPoli-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/tienda.war
    ports:
      - "8080:8080"

volumes:
  mysql_data:

