# Usa la imagen de Tomcat con JDK 21
FROM tomcat:10.1.24-jdk21-temurin-jammy

# Copia el archivo WAR a la carpeta de despliegue de Tomcat
COPY ./target/PaginaWebPoli-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/PaginaWebPoli.war

# Comando para iniciar Tomcat
CMD ["catalina.sh", "run"]
