# Usa la imagen más reciente de MySQL
FROM mysql:latest

# Establecer las variables de entorno
ENV MYSQL_ROOT_PASSWORD=1234
ENV MYSQL_DATABASE=javaweb
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=1234

# Copiar archivos de configuración y script de inicialización
COPY ./init.sql /docker-entrypoint-initdb.d/init.sql
COPY ./my.cnf /etc/mysql/conf.d/my.cnf

# Exponer el puerto por defecto de MySQL
EXPOSE 3307

